#!/bin/bash

sudo apt-get update -y && apt-get install curl git -y 
curl -sL https://deb.nodesource.com/setup_14.x  | bash -

sudo apt-get install nodejs -y

echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> /root/.npmrc

npm install
npm run build
